### ISSUE TITLE
stabilityai/stable-diffusion-2-1 does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by HaoqianSong** [Tsingularity/dift#23]
Hello, when I ran the demo, stabilityai/stable-diffusion-2-1 does not appear to have a file named config.json. This means that config.json cannot be obtained. I would like to ask where to download the file? The specific error reported is as follows:

/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa269a40d90>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-diffusion-2-1/resolve/main/unet/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa269a40d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-diffusion-2-1/resolve/main/unet/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa269a40d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 1efb8410-3b12-49f4-b553-4de46f64da86)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 337, in load_config
    config_file = hf_hub_download(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcl/DETR/SDAseg/others/DIFT-main/demo.py", line 14, in <module>
    dift = SDFeaturizer()
  File "/home/pcl/DETR/SDAseg/others/DIFT-main/src/models/dift_sd.py", line 192, in __init__
    unet = MyUNet2DConditionModel.from_pretrained(sd_id, subfolder="unet")
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 472, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-2-1 does not appear to have a file named config.json.

**Comment by Tsingularity** [comment]
Hi, this seems to be a issue of diffusers versions. Could you please follow the instructions [here](https://github.com/Tsingularity/dift?tab=readme-ov-file#prerequisites) and install our provided conda environment, then see how it goes?

**Comment by HaoqianSong** [comment]
conda env create -f environment.yml and setup_env.sh. I have tried both environment installation methods, but still have the same problem of missing config.json file. Can I manually download the file and configure it? Where is the specific configuration and download location? The relevant error reports are as follows:

Traceback (most recent call last):
  File "/home/pcl/Minconda/conda3/envs/dift1/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 337, in load_config
    config_file = hf_hub_download(
  File "/home/pcl/Minconda/conda3/envs/dift1/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/pcl/Minconda/conda3/envs/dift1/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pcl/DETR/SDAseg/others/DIFT-main/demo.py", line 14, in <module>
    dift = SDFeaturizer()
  File "/home/pcl/DETR/SDAseg/others/DIFT-main/src/models/dift_sd.py", line 192, in __init__
    unet = MyUNet2DConditionModel.from_pretrained(sd_id, subfolder="unet")
  File "/home/pcl/Minconda/conda3/envs/dift1/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 472, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/pcl/Minconda/conda3/envs/dift1/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-2-1 does not appear to have a file named config.json.

**Comment by Tsingularity** [comment]
Given the error message you shared, seems to be an internet connection issue?
```
File "/home/pcl/Minconda/conda3/envs/dift1/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1291, in hf_hub_download
raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.
```

**Comment by zyfone** [comment]
i also meet this issue, you can solve this issue by the "export HF_ENDPOINT=https://hf-mirror.com"

**Comment by HaoqianSong** [comment]
Thanks
