### ISSUE TITLE
Enviornment Setting Issue

### ISSUE THREAD

**Issue by Chinafsh** [Tsingularity/dift#28]
Hello, love ur work.
I have a setting issue when I go through your setting step.
my OS is Ubuntu 22.04, CUDA version is 11.7
I followed the suggestion : 
conda env create -f environment.yml
conda activate dift

it's good so far.
but when I key in:
python extract_dift.py \
    --input_path ./assets/cat.png \
    --output_path dift_cat.pt \
    --img_size 768 768 \
    --t 261 \
    --up_ft_index 1 \
    --prompt 'a photo of a cat' \
    --ensemble_size 8 

an error occurs:
Traceback (most recent call last):
  File "/home/xxx/Documents/Diffusion/DiFT/dift-main/extract_dift.py", line 4, in <module>
    from torchvision.transforms import PILToTensor
  File "/home/xxx/.local/lib/python3.10/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/home/xxx/.local/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 4, in <module>
    import torch._custom_ops
ModuleNotFoundError: No module named 'torch._custom_ops'

do u encounter this before or could u give any advice. Thx first. @Tsingularity

**Comment by Chinafsh** [comment]
I changed the setting version, it works now.
